### PR TITLE
+ whitespace formatting; s/utf-8/UTF-8/

### PR DESCRIPTION
**Pull request by haoess**

### CODE REVIEW

**Comment by wrznr** [comment]
@tboenig Pls. implement the changes proposed in this PR in the latest version of `hocr2tei.xsl`.

**Comment by zuphilip** [comment]
Also this issue is now marked as stale (because no review was done) and there are merge conflicts, I would very much support the changes requested here. Especially normalizing the spacing is IMO heavily needed. How can we achieve this?

**Comment by wrznr** [comment]
I added @kba as a reviewer since I am not fluent with XSLT and @tboenig obviously does not find the time.

**Comment by wrznr** [comment]
Maybe @haoess is even ready to solve the conflicts?

**Comment by wrznr** [comment]
@haoess Thank you!

**Comment by zuphilip** [comment]
:rocket: Thank you very much @haoess  for the work and @wrznr for merging! :bowing_man:

**Pull request merged**
